<?php

/**
 * @file
 * Contains od_ext_suggested_app.module.
 */

use Drupal\Core\Url;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function od_ext_rate_theme($existing, $type, $theme, $path) {
  return [
    'rate_template_fiveleaf' => [
      'variables' => [
        'star1_votes' => 0,
        'star2_votes' => 0,
        'star3_votes' => 0,
        'star4_votes' => 0,
        'star5_votes' => 0,
        'use_ajax' => FALSE,
        'can_vote' => FALSE,
        'has_voted' => FALSE,
        'entity_id' => NULL,
        'entity_type_id' => NULL,
      ],
      'template' => 'rate-template-fiveleaf',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_rate_template_fiveleaf(&$variables) {
  $variables['stars'] = [];

  // Calculate the score.
  $score = 0;
  $total_votes = 0;
  for ($counter = 1; $counter < 6; $counter++) {
    $score += ($variables['star' . $counter . '_votes'] * $counter);
    $total_votes += $variables['star' . $counter . '_votes'];
  }
  if ($score > 0 && $total_votes > 0) {
    $score = round($score / $total_votes);
  }

  // Set up the links.
  for ($counter = 1; $counter < 6; $counter++) {
    $variables['stars'][$counter]['star_attributes'] = new Attribute();
    $variables['stars'][$counter]['star_attributes']['class'] = [];

    if ($counter <= $score) {
      $variables['stars'][$counter]['star_attributes']['class'][] = 'rate-fiveleaf-btn-filled';
    }
    else {
      $variables['stars'][$counter]['star_attributes']['class'][] = 'rate-fiveleaf-btn-empty';
    }
    $variables['stars'][$counter]['star_attributes']['class'][] = ' rate-fiveleaf-' . $counter;

    if ($variables['use_ajax'] && !$variables['has_voted'] && $variables['can_vote']) {
      $variables['stars'][$counter]['star_attributes']['class'][] = 'use-ajax';
    }

    $variables['stars'][$counter]['star_link'] = Url::fromRoute('rate.vote', [
      'entity_type_id' => $variables['entity_type_id'],
      'vote_type_id' => 'star' . $counter,
      'entity_id' => $variables['entity_id'],
      'destination' => drupal_get_destination()['destination'],
    ])->toString();

    $variables['stars'][$counter]['star_img'] = file_get_contents(drupal_get_path('module', 'od_ext_rate') . '/images/fiveleaf.svg');
  }

  _rate_set_common_theme_variables($variables, FALSE);
  _rate_get_undo_link($variables);
  $variables['#attached']['library'][] = 'od_ext_rate/fiveleaf';
}
